/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.vistas;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Alumno;
import modelo.Conexion;
import modelo.Materia;
import modelo.MateriaData;

/**
 *
 * @author Martin
 */
public class VistaMaterias extends javax.swing.JInternalFrame {

    Conexion con = new Conexion();
    MateriaData md = new MateriaData(con);
    
     String nombre;
     String responsable;
     String periodo;
    
    /**
     * Creates new form VistaMaterias
     */
    public VistaMaterias() {
        initComponents();
    }
    
     private void limpiar(){          
         tbIdMat.setText("");
        tbNombreMat.setText("");
        tbResponsableMat.setText("");
        tbPeriodoMat.setText("");
        tbResponsableMat.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbIdMat = new javax.swing.JLabel();
        tbIdMat = new javax.swing.JTextField();
        btnBuscarMat = new javax.swing.JButton();
        btnModificarMat = new javax.swing.JButton();
        btnGuardarMat = new javax.swing.JButton();
        btnLimpiarMat = new javax.swing.JButton();
        btnEliminarMat = new javax.swing.JButton();
        lbResponsable = new javax.swing.JLabel();
        lbPeriodo = new javax.swing.JLabel();
        lbNombreMat = new javax.swing.JLabel();
        tbResponsableMat = new javax.swing.JTextField();
        tbNombreMat = new javax.swing.JTextField();
        tbPeriodoMat = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Materias");

        lbIdMat.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lbIdMat.setText("Codigo materia");

        tbIdMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIdMatActionPerformed(evt);
            }
        });
        tbIdMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbIdMatKeyTyped(evt);
            }
        });

        btnBuscarMat.setText("Buscar");
        btnBuscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMatActionPerformed(evt);
            }
        });

        btnModificarMat.setText("Modificar");
        btnModificarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMatActionPerformed(evt);
            }
        });

        btnGuardarMat.setText("Guardar");
        btnGuardarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMatActionPerformed(evt);
            }
        });

        btnLimpiarMat.setText("Limpiar");
        btnLimpiarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMatActionPerformed(evt);
            }
        });

        btnEliminarMat.setText("Eliminar");
        btnEliminarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMatActionPerformed(evt);
            }
        });

        lbResponsable.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lbResponsable.setText("Responsable");

        lbPeriodo.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lbPeriodo.setText("Periodo");

        lbNombreMat.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lbNombreMat.setText("Nombre materia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarMat)
                        .addGap(34, 34, 34)
                        .addComponent(btnModificarMat)
                        .addGap(31, 31, 31)
                        .addComponent(btnEliminarMat)
                        .addGap(33, 33, 33)
                        .addComponent(btnLimpiarMat))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbPeriodo)
                            .addComponent(lbNombreMat)
                            .addComponent(lbResponsable)
                            .addComponent(lbIdMat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tbNombreMat)
                                        .addComponent(tbResponsableMat)
                                        .addComponent(tbPeriodoMat, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tbIdMat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                                    .addComponent(btnBuscarMat))))))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdMat)
                    .addComponent(tbIdMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreMat)
                    .addComponent(tbNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResponsable)
                    .addComponent(tbResponsableMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPeriodo)
                    .addComponent(tbPeriodoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarMat)
                    .addComponent(btnLimpiarMat)
                    .addComponent(btnEliminarMat)
                    .addComponent(btnGuardarMat))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbIdMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbIdMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbIdMatActionPerformed

    private void btnGuardarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMatActionPerformed
        // TODO add your handling code here:
         
         if((tbNombreMat.getText().isEmpty()) 
             || tbPeriodoMat.getText().isEmpty() || tbResponsableMat.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Ingrese datos", "Info", JOptionPane.WARNING_MESSAGE);  
         }else{
        nombre= tbNombreMat.getText();
        responsable=tbResponsableMat.getText();
        periodo=tbPeriodoMat.getText();
        Materia materia = new Materia(nombre,responsable,periodo);
          try {
               md.guardarMateria(materia);
           } catch (SQLException ex) {
           Logger.getLogger(VistaMaterias.class.getName()).log(Level.SEVERE, null, ex);
           }
        tbIdMat.setText(materia.getId()+"");
         }
          JOptionPane.showMessageDialog(null, "Se guardo materia", "Info", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnGuardarMatActionPerformed

    private void btnLimpiarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMatActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarMatActionPerformed

    private void btnBuscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMatActionPerformed
        // TODO add your handling code here:
        
        int id;
        String nombre;
         if((tbIdMat.getText().isEmpty()) && tbNombreMat.getText().isEmpty())  {
           JOptionPane.showMessageDialog(null, "Ingrese codigo o nombre", "Info", JOptionPane.WARNING_MESSAGE);  
         }
         else {
          if(!tbIdMat.getText().isEmpty()){     
           
          id=Integer.parseInt(tbIdMat.getText());             
          Materia mat= md.buscarMateria(id);
          if (mat !=null){
            tbIdMat.setText(mat.getId()+"");
            tbNombreMat.setText(mat.getNombre());
            tbResponsableMat.setText( mat.getResponsable());
            tbPeriodoMat.setText( mat.getPeriodo());  
            
        } else {
         JOptionPane.showMessageDialog(null, "La materia no existe", "Info", JOptionPane.WARNING_MESSAGE); 
        }
         }
        if (!tbNombreMat.getText().isEmpty()){  
        nombre=tbNombreMat.getText();             
        Materia mat= md.buscarMateriaXNombre(nombre);
        if (mat !=null){
        tbIdMat.setText(mat.getId()+"");
            tbNombreMat.setText(mat.getNombre());
            tbResponsableMat.setText( mat.getResponsable());
            tbPeriodoMat.setText( mat.getPeriodo()); 
        } else {
         JOptionPane.showMessageDialog(null, "La materia no existe", "Info", JOptionPane.WARNING_MESSAGE); 
        } 
           // }   
           }       
        }
    }//GEN-LAST:event_btnBuscarMatActionPerformed

    private void btnModificarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMatActionPerformed
        // TODO add your handling code here:}
         if((tbIdMat.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un codigo de materia", "Eliminar", JOptionPane.WARNING_MESSAGE); 
        }else{ 
        int id=Integer.parseInt(tbIdMat.getText());
        nombre= tbNombreMat.getText();
        responsable=tbResponsableMat.getText();
        periodo=tbPeriodoMat.getText();
        
        Materia materia = new Materia(id,nombre,responsable,periodo);
        md.actualizarMateria(materia);
        JOptionPane.showMessageDialog(null, "Se actualizo Materia", "Info", JOptionPane.WARNING_MESSAGE); 
         }
    }//GEN-LAST:event_btnModificarMatActionPerformed

    private void btnEliminarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMatActionPerformed
        // TODO add your handling code here:
        if((tbIdMat.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un codigo de materia", "Eliminar", JOptionPane.WARNING_MESSAGE); 
        }else{
        int id=Integer.parseInt(tbIdMat.getText());
            try {
               boolean seElimino= md.borrarMateria(id);
               if(seElimino) JOptionPane.showMessageDialog(null, "Se elimino materia", "Info", JOptionPane.WARNING_MESSAGE); 
            } catch (SQLException ex) {
                Logger.getLogger(VistaMaterias.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       limpiar();
    }//GEN-LAST:event_btnEliminarMatActionPerformed

    private void tbIdMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbIdMatKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();      
          if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
                // Error.setText("Ingresa Solo Numeros");
          } 
    }//GEN-LAST:event_tbIdMatKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMat;
    private javax.swing.JButton btnEliminarMat;
    private javax.swing.JButton btnGuardarMat;
    private javax.swing.JButton btnLimpiarMat;
    private javax.swing.JButton btnModificarMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbIdMat;
    private javax.swing.JLabel lbNombreMat;
    private javax.swing.JLabel lbPeriodo;
    private javax.swing.JLabel lbResponsable;
    private javax.swing.JTextField tbIdMat;
    private javax.swing.JTextField tbNombreMat;
    private javax.swing.JTextField tbPeriodoMat;
    private javax.swing.JTextField tbResponsableMat;
    // End of variables declaration//GEN-END:variables
}
