/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timerjframe;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author juanj
 */
public class frmConTimer extends javax.swing.JFrame {
    Timer tiempo;
    //LocalDate fecha = LocalDate.now();
    //LocalTime hora = LocalTime.of(14, 5, 5);
   // LocalDateTime horaProgramada = LocalDateTime.of(fecha, hora);
    /**
     * Creates new form frmConTimer
     */
    LocalDateTime horaProgramada = LocalDateTime.now().withNano(0).plusSeconds(10);
    public frmConTimer() {
        initComponents();
        tiempo = new Timer(1000, null);
        tiempo.start();
        
        tiempo.addActionListener(new java.awt.event.ActionListener(){
          
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt){
                    operacionQueHaraElTimer();
            }

            private void operacionQueHaraElTimer() {
                
                lblReloj.setText(new Date().toString());
                System.out.println("Mostrando accion del timer"+ LocalDateTime.now().withNano(0));
                System.out.println("programada: " + horaProgramada);
                System.out.println("son??: " + (LocalDateTime.now().withNano(0).equals((LocalDateTime)horaProgramada)));
                //withNano Devuelve una copia de LocalDateTime con los nano segundos alterados.
                if(LocalDateTime.now().withNano(0).equals((LocalDateTime)horaProgramada)){
                    lblRecuerda.setText("Recuerda: Debes efectuar la compra de los siguientes ítems: Ejes, y Semiejes medianos.");
                    System.out.println("Holis...");
                }
            }
        });  // lleva un actionListener que hacemos new
        //tiempo.schedule(operacionQueHaraElTimer,20,2000);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        lblRecuerda = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCompara = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        setForeground(new java.awt.Color(102, 102, 0));

        jLabel2.setText("Actualizando la hora del reloj...");

        lblReloj.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnLimpiar.setText("Reprogramar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        lblRecuerda.setBackground(new java.awt.Color(255, 255, 153));
        lblRecuerda.setForeground(new java.awt.Color(255, 51, 51));
        lblRecuerda.setText("holis");
        lblRecuerda.setToolTipText("");
        lblRecuerda.setAutoscrolls(true);
        lblRecuerda.setBorder(new javax.swing.border.MatteBorder(null));

        jMenu1.setText("Archivo");

        jMenuItemCompara.setText("CompararFechas");
        jMenuItemCompara.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuItemCompara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComparaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCompara);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblRecuerda, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblRecuerda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar1)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        horaProgramada = horaProgramada.plusMinutes(1);
        horaProgramada.plusSeconds(5);
        lblRecuerda.setText("Reprogramada para: " +horaProgramada);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        lblRecuerda.setText("");
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void jMenuItemComparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComparaActionPerformed
        // TODO add your handling code here:
        LocalDateTime date1 = LocalDateTime.now();
        System.out.print(date1.isBefore(horaProgramada)); //muestra true (verdadero)
        System.out.print(date1.isAfter(horaProgramada)); //muestra false (falso)
    }//GEN-LAST:event_jMenuItemComparaActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCompara;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRecuerda;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables
}
