/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.vistas;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.AlumnoData;
import modelo.Conexion;
import modelo.Materia;
import modelo.MateriaData;

/**
 *
 * @author Martin
 */
public class VistaListadoMaterias extends javax.swing.JInternalFrame {
       private DefaultTableModel modelo;
 //private ArrayList<Cursada> listaCursada;
 private ArrayList<Materia> listaMateria;
//// private CursadaData cd;
 private MateriaData md;
 private Conexion con;
// private AlumnoData ad;
 //private ArrayList <Alumno> listaAlumno;


    /**
     * Creates new form VistaListadoMaterias
     */
    public VistaListadoMaterias() {
        initComponents();
         con =new Conexion();
        modelo= new DefaultTableModel();
                      
        md= new MateriaData(con);
        listaMateria=(ArrayList<Materia>)md.obtenerMaterias();
      
        borrarFilasTabla();
        armarCabaceraTabla();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListadoMaterias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoMaterias = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblListadoMaterias.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblListadoMaterias.setText("Listado de materias");

        tblListadoMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListadoMaterias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(lblListadoMaterias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblListadoMaterias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void armarCabaceraTabla(){
    ArrayList<Object> columns= new ArrayList<>();
    columns.add("ID");
    columns.add("Nombre");
    columns.add("Responsable");
    columns.add("Periodo");
    
    for (Object it:columns)
    {
        modelo.addColumn(it);
    }
    tblListadoMaterias.setModel(modelo);
    }
    
    public void borrarFilasTabla(){
     int a=modelo.getRowCount()-1 ;
          
     
     for (int i=a;i>=0;i--){
     modelo.removeRow(i);
     }
    }
    
    private void cargarDatos(){
     borrarFilasTabla();
    // Materia mat=(Materia)cbMaterias.getSelectedItem();
     
    for (Materia mat:listaMateria){     
       modelo.addRow(new Object[]{mat.getId(),mat.getNombre(),mat.getResponsable(),mat.getPeriodo()});
        }
  
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListadoMaterias;
    private javax.swing.JTable tblListadoMaterias;
    // End of variables declaration//GEN-END:variables
}
