/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasUniversidad;


/**
 *
 * @kaiserkey
 */
public class Universidad extends javax.swing.JFrame {

    /**
     * Creates new form Universidad
     */
    public Universidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        FArchivo = new javax.swing.JMenu();
        MSalir = new javax.swing.JMenuItem();
        FAlumno = new javax.swing.JMenu();
        MFAlumno = new javax.swing.JMenuItem();
        MFBuscarAlumno = new javax.swing.JMenuItem();
        MFActualizarAlumnos = new javax.swing.JMenuItem();
        FMateria = new javax.swing.JMenu();
        MFMaterias = new javax.swing.JMenuItem();
        MFBuscarMaterias = new javax.swing.JMenuItem();
        MFActualizarMaterias = new javax.swing.JMenuItem();
        FCursada = new javax.swing.JMenu();
        MFCursadas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        FArchivo.setText("Archivo");

        MSalir.setText("Salir");
        MSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSalirActionPerformed(evt);
            }
        });
        FArchivo.add(MSalir);

        jMenuBar1.add(FArchivo);

        FAlumno.setText("Alumnos");

        MFAlumno.setText("Formulario Alumnos");
        MFAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFAlumnoActionPerformed(evt);
            }
        });
        FAlumno.add(MFAlumno);

        MFBuscarAlumno.setText("Buscar Alumnos");
        MFBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFBuscarAlumnoActionPerformed(evt);
            }
        });
        FAlumno.add(MFBuscarAlumno);

        MFActualizarAlumnos.setText("Actualizar Alumnos");
        MFActualizarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFActualizarAlumnosActionPerformed(evt);
            }
        });
        FAlumno.add(MFActualizarAlumnos);

        jMenuBar1.add(FAlumno);

        FMateria.setText("Materias");

        MFMaterias.setText("Formulario Materias");
        MFMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFMateriasActionPerformed(evt);
            }
        });
        FMateria.add(MFMaterias);

        MFBuscarMaterias.setText("Buscar Materias");
        MFBuscarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFBuscarMateriasActionPerformed(evt);
            }
        });
        FMateria.add(MFBuscarMaterias);

        MFActualizarMaterias.setText("Actualizar Materias");
        MFActualizarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFActualizarMateriasActionPerformed(evt);
            }
        });
        FMateria.add(MFActualizarMaterias);

        jMenuBar1.add(FMateria);

        FCursada.setText("Cursadas");

        MFCursadas.setText("Formulario Cursadas");
        MFCursadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFCursadasActionPerformed(evt);
            }
        });
        FCursada.add(MFCursadas);

        jMenuItem1.setText("Buscar Cursada");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        FCursada.add(jMenuItem1);

        jMenuItem2.setText("Actualizar Cursadas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        FCursada.add(jMenuItem2);

        jMenuBar1.add(FCursada);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MSalirActionPerformed

    private void MFAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFAlumnoActionPerformed
        VistaCargarAlumnos va = new VistaCargarAlumnos();
        Escritorio.removeAll();
        Escritorio.repaint();
        va.setVisible(true);
        Escritorio.add(va);
        Escritorio.moveToFront(va);
        
    }//GEN-LAST:event_MFAlumnoActionPerformed

    private void MFBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFBuscarAlumnoActionPerformed
        VistaBuscarBorrarAlumno b = new VistaBuscarBorrarAlumno();
        Escritorio.removeAll();
        Escritorio.repaint();
        b.setVisible(true);
        Escritorio.add(b);
        Escritorio.moveToFront(b);
    }//GEN-LAST:event_MFBuscarAlumnoActionPerformed

    private void MFActualizarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFActualizarAlumnosActionPerformed
        VistaActualizarAlumno ba = new VistaActualizarAlumno();
        Escritorio.removeAll();
        Escritorio.repaint();
        ba.setVisible(true);
        Escritorio.add(ba);
        Escritorio.moveToFront(ba);
    }//GEN-LAST:event_MFActualizarAlumnosActionPerformed

    private void MFMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFMateriasActionPerformed
        VistaCargarMateria ca = new VistaCargarMateria();
        Escritorio.removeAll();
        Escritorio.repaint();
        ca.setVisible(true);
        Escritorio.add(ca);
        Escritorio.moveToFront(ca);
    }//GEN-LAST:event_MFMateriasActionPerformed

    private void MFBuscarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFBuscarMateriasActionPerformed
        VistaBuscarBorrarMateria bm = new VistaBuscarBorrarMateria();
        Escritorio.removeAll();
        Escritorio.repaint();
        bm.setVisible(true);
        Escritorio.add(bm);
        Escritorio.moveToFront(bm);
    }//GEN-LAST:event_MFBuscarMateriasActionPerformed

    private void MFActualizarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFActualizarMateriasActionPerformed
        VistaActualizarMateria am = new VistaActualizarMateria();
        Escritorio.removeAll();
        Escritorio.repaint();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
    }//GEN-LAST:event_MFActualizarMateriasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VistaActualizarCursada ac = new VistaActualizarCursada();
        Escritorio.removeAll();
        Escritorio.repaint();
        ac.setVisible(true);
        Escritorio.add(ac);
        Escritorio.moveToFront(ac);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MFCursadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFCursadasActionPerformed
        VistaCargarCursada cc = new VistaCargarCursada();
        Escritorio.removeAll();
        Escritorio.repaint();
        cc.setVisible(true);
        Escritorio.add(cc);
        Escritorio.moveToFront(cc);
    }//GEN-LAST:event_MFCursadasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        VistaBuscarBorrarCursada bc = new VistaBuscarBorrarCursada();
        Escritorio.removeAll();
        Escritorio.repaint();
        bc.setVisible(true);
        Escritorio.add(bc);
        Escritorio.moveToFront(bc);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Universidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu FAlumno;
    private javax.swing.JMenu FArchivo;
    private javax.swing.JMenu FCursada;
    private javax.swing.JMenu FMateria;
    private javax.swing.JMenuItem MFActualizarAlumnos;
    private javax.swing.JMenuItem MFActualizarMaterias;
    private javax.swing.JMenuItem MFAlumno;
    private javax.swing.JMenuItem MFBuscarAlumno;
    private javax.swing.JMenuItem MFBuscarMaterias;
    private javax.swing.JMenuItem MFCursadas;
    private javax.swing.JMenuItem MFMaterias;
    private javax.swing.JMenuItem MSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
