/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasUniversidad;

import ModeloUniversidad.*;

/**
 *
 * @author Marcos
 */
public class VistaBuscarBorrarMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaBuscarBorrarMateria
     */
    public VistaBuscarBorrarMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TBCodigo = new javax.swing.JTextField();
        BTNBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TMaterias = new javax.swing.JTable();
        BTBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTMostrarTodo = new javax.swing.JButton();

        jLabel2.setText("Codigo de Materia");

        BTNBuscar.setText("Buscar");
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });

        TMaterias.setAutoCreateRowSorter(true);
        TMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Responsable", "Periodo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TMaterias);

        BTBorrar.setText("Borrar");
        BTBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBorrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Buscar Materias");

        BTMostrarTodo.setText("Mostrar Todo");
        BTMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMostrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(TBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTNBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTMostrarTodo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(BTBorrar)))
                        .addGap(0, 169, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBuscar)
                    .addComponent(BTMostrarTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTBorrar)
                .addGap(161, 161, 161))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        int id;
        id = Integer.parseInt(TBCodigo.getText());
        Conexion con = new Conexion();
        con.crearConexion();
        con.getConexion();
        Materia m = new Materia();
        m.setIDMateria(id);
        MateriaData md = new MateriaData(con);
        md.buscarMateria(m);
        mostrarResultados(m);

    }//GEN-LAST:event_BTNBuscarActionPerformed

    private void BTBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBorrarActionPerformed
        int id;
        id = Integer.parseInt(TBCodigo.getText());
        Conexion con = new Conexion();
        con.crearConexion();
        con.getConexion();
        Materia m = new Materia();
        m.setIDMateria(id);
        MateriaData md = new MateriaData(con);
        md.buscarMateria(m);
        md.borrarMateria(m.getIDMateria());
    }//GEN-LAST:event_BTBorrarActionPerformed

    private void BTMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMostrarTodoActionPerformed
        Conexion con = new Conexion();
        con.crearConexion();
        con.getConexion();
        MateriaData md = new MateriaData(con);
        md.ListarMateriasBD();
        mostrarTodo(md);
    }//GEN-LAST:event_BTMostrarTodoActionPerformed

    public void mostrarResultados(Materia materia){
                TMaterias.setAutoCreateRowSorter(true);
        TMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {materia.getIDMateria(), materia.getNombre(), materia.getResponsable(), materia.getPeriodo()}
            },
            new String [] {
                "Codigo", "Nombre", "Responsable", "Periodo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    
    public void mostrarTodo(MateriaData md){
        TBCodigo.setText("");
        String matrisMateriasBD[][] = new String[md.getMateriasBD().size()][4];
        
        for(int i = 0; i < md.getMateriasBD().size(); i++){
            matrisMateriasBD[i][0]= String.valueOf(md.getMateriasBD().get(i).getIDMateria());
            matrisMateriasBD[i][1] = md.getMateriasBD().get(i).getNombre();
            matrisMateriasBD[i][2] = md.getMateriasBD().get(i).getResponsable();
            matrisMateriasBD[i][3] = String.valueOf(md.getMateriasBD().get(i).getPeriodo());
            
        }
        
        TMaterias.setAutoCreateRowSorter(true);
        TMaterias.setModel(new javax.swing.table.DefaultTableModel(
            matrisMateriasBD,
            new String [] {
                "Codigo", "Nombre", "Responsable", "Periodo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBorrar;
    private javax.swing.JButton BTMostrarTodo;
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JTextField TBCodigo;
    private javax.swing.JTable TMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
