/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasUniversidad;

import ModeloUniversidad.*;

/**
 *
 * @author Marcos
 */
public class VistaActualizarCursada extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaActualizarCursada
     */
    public VistaActualizarCursada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TBCodigoCursada = new javax.swing.JTextField();
        TBCodigoAlumno = new javax.swing.JTextField();
        TBCodigoMateria = new javax.swing.JTextField();
        TBNota = new javax.swing.JTextField();
        BTActualizar = new javax.swing.JButton();
        BTBuscar = new javax.swing.JButton();
        BTLimpiar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Actualizar Cursada ");

        jLabel2.setText("Codigo de Alumno:");

        jLabel3.setText("Codigo de Materia:");

        jLabel4.setText("Codigo de Cursada:");

        jLabel5.setText("Nota:");

        TBCodigoCursada.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        TBCodigoAlumno.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TBCodigoAlumno.setEnabled(false);
        TBCodigoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBCodigoAlumnoActionPerformed(evt);
            }
        });

        TBCodigoMateria.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TBCodigoMateria.setEnabled(false);
        TBCodigoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBCodigoMateriaActionPerformed(evt);
            }
        });

        TBNota.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        BTActualizar.setText("Actualizar");
        BTActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActualizarActionPerformed(evt);
            }
        });

        BTBuscar.setText("Buscar");
        BTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBuscarActionPerformed(evt);
            }
        });

        BTLimpiar.setText("LimpiarTB");
        BTLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TBNota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(TBCodigoMateria, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TBCodigoAlumno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TBCodigoCursada, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(40, 40, 40)
                                .addComponent(BTBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(BTActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(BTLimpiar)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TBCodigoCursada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTBuscar))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TBCodigoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TBCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TBNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTActualizar)
                    .addComponent(BTLimpiar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBCodigoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBCodigoMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBCodigoMateriaActionPerformed

    private void BTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBuscarActionPerformed
        int id;
        id = Integer.parseInt(TBCodigoCursada.getText());
        
        Conexion con = new Conexion();
        con.crearConexion();
        con.getConexion();
        
        Cursada c = new Cursada();
        c.setIDCursada(id);
        AlumnoData ad = new AlumnoData(con);
        MateriaData md = new MateriaData(con);
        
        CursadaData cd = new CursadaData(con);
        cd.buscarCursadas(c, md, ad);
        
        TBCodigoCursada.setText(String.valueOf(c.getIDCursada()));
        TBCodigoAlumno.setText(String.valueOf(c.getAlumno().getIDAlumno()));
        TBCodigoMateria.setText(String.valueOf(c.getMateria().getIDMateria()));
        TBNota.setText(String.valueOf(c.getNota()));
        
        
        
    }//GEN-LAST:event_BTBuscarActionPerformed

    private void BTActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActualizarActionPerformed
        int id_cursada = Integer.parseInt(TBCodigoCursada.getText());
        int id_materia = Integer.parseInt(TBCodigoMateria.getText());
        int id_alumno = Integer.parseInt(TBCodigoAlumno.getText());
        
        Conexion con = new Conexion();
        con.crearConexion();
        con.getConexion();
        
        Alumno al = new Alumno();
        al.setID_Alumno(id_alumno);
        Materia m = new Materia();
        m.setIDMateria(id_materia);
        Cursada c = new Cursada();
        c.setIDCursada(id_cursada);
        c.setNota(Integer.parseInt(TBNota.getText()));
        
        CursadaData cd = new CursadaData(con);
        cd.actualizarNotaCursada(al, m, c);
    }//GEN-LAST:event_BTActualizarActionPerformed

    private void BTLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLimpiarActionPerformed
        TBCodigoMateria.setText("");
        TBCodigoAlumno.setText("");
        TBCodigoCursada.setText("");
        TBNota.setText("");
    }//GEN-LAST:event_BTLimpiarActionPerformed

    private void TBCodigoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBCodigoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBCodigoAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTActualizar;
    private javax.swing.JButton BTBuscar;
    private javax.swing.JButton BTLimpiar;
    private javax.swing.JTextField TBCodigoAlumno;
    private javax.swing.JTextField TBCodigoCursada;
    private javax.swing.JTextField TBCodigoMateria;
    private javax.swing.JTextField TBNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
